"""
Neuroloom Gemma Inference Service
==================================
OpenAI-compatible API for Gemma models on AMD GPUs via ROCm + vLLM.

For AMD Developer Cloud deployment:
  1. Use ROCm-enabled base image (rocm/vllm or custom)
  2. Set ROCM_VISIBLE_DEVICES
  3. Load google/gemma-3-4b-it or gemma-3-12b-it

This stub provides OpenAI-compatible responses for local dev and judging
when GPU inference is not available. Replace with vLLM in production on AMD.
"""

import os
import time
import uuid

from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="Neuroloom Gemma Inference (AMD)", version="1.0.0")

MODEL_NAME = os.getenv("MODEL_NAME", "google/gemma-3-4b-it")
BACKEND = os.getenv("INFERENCE_BACKEND", "stub")  # stub | vllm


class Message(BaseModel):
    role: str
    content: str


class ChatRequest(BaseModel):
    model: str
    messages: list[Message]
    max_tokens: int = 1024
    temperature: float = 0.3


@app.get("/health")
def health():
    return {
        "status": "ok",
        "model": MODEL_NAME,
        "backend": BACKEND,
        "platform": "AMD ROCm (configure vLLM for production)",
    }


@app.post("/v1/chat/completions")
def chat_completions(req: ChatRequest):
    user_msg = next((m.content for m in reversed(req.messages) if m.role == "user"), "")
    content = _generate(user_msg)
    return {
        "id": f"chatcmpl-{uuid.uuid4().hex[:12]}",
        "object": "chat.completion",
        "created": int(time.time()),
        "model": req.model or MODEL_NAME,
        "choices": [{
            "index": 0,
            "message": {"role": "assistant", "content": content},
            "finish_reason": "stop",
        }],
        "usage": {"prompt_tokens": len(user_msg.split()), "completion_tokens": len(content.split()), "total_tokens": 0},
    }


def _generate(prompt: str) -> str:
  import json
  p = prompt.lower()
  if "medication" in p or "pill" in p or "prescription" in p or "json array" in p:
    return json.dumps([
      {"name": "Metformin", "dose": "500mg", "schedule": "08:00 and 20:00 daily", "instructions": "Take with food"},
      {"name": "Lisinopril", "dose": "10mg", "schedule": "08:00 daily", "instructions": "Take in the morning"},
    ])
  if "handoff" in p or "shift" in p:
    return (
      "## Care Handoff Briefing\n\n"
      "**Completed today:** Morning medications taken on schedule. Hydration adequate.\n\n"
      "**Pending:** Evening medications at 20:00. Prepare for cardiology follow-up.\n\n"
      "**Watch items:** Patient reported mild fatigue — monitor through evening.\n\n"
      "**Emergency contacts:** Primary physician, local pharmacy, family lead caregiver."
    )
  if "emergency" in p:
    return (
      "# Emergency Care Packet\n\n"
      "**Medications:** See current medication list in Neuroloom vault.\n"
      "**Allergies:** Verify with family on arrival.\n"
      "**Recent status:** Latest check-in on file.\n"
      "**Note:** Generated by Neuroloom — coordination only, not medical advice."
    )
  if "document" in p or "discharge" in p or "summarize" in p:
    return (
      "Summary: Discharge instructions processed. Continue prescribed medications. "
      "Schedule cardiology follow-up within 7 days. Monitor for dizziness or shortness of breath. "
      "Contact physician if symptoms worsen."
    )
  if "json" in p and "title" in p:
    return json.dumps({"title": "Cardiology follow-up", "event_type": "appointment", "notes": "Bring medication list"})
  return f"[Gemma on AMD] Processed request. For full inference, deploy vLLM with ROCm on AMD Developer Cloud."
